title: AWS App Runner Cross-Tenant Information Leak (ListObservabilityConfigurationsForAccount)
slug: aws-app-runner-list-observability-configurations-for-account
cves: null
affectedPlatforms:
- AWS
affectedServices:
- App Runner
image: <Please Fill In>
severity: Low
discoveredBy:
  name: Nick Frichette
  org: Nick Frichette
  domain: https://frichetten.com
  twitter: frichette_n
publishedAt: 2023/04/03
disclosedAt: 2023/02/28
exploitabilityPeriod: Until 2023/03/13
knownITWExploitation: false
summary: |
  The API action ListObservabilityConfigurationsForAccount did not properly validate the 
  "AccountId" parameter that was passed to it. As a result, any account ID could be provided 
  and the API would return the information for that account. This would like minor information
  about the observability configuration for App Runner in the account.
manualRemediation: |
  None required
detectionMethods: null
contributor: https://github.com/frichetten
references:
- https://frichetten.com/blog/minor-cross-tenant-vulns-app-runner
